/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardHttp: typeof import('./src/components/CardHttp.vue')['default']
    CardsHttp: typeof import('./src/components/CardsHttp.vue')['default']
    CardsList: typeof import('./src/components/CardsList.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    FloatingButton: typeof import('./src/components/FloatingButton.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    StatusDialog: typeof import('./src/components/StatusDialog.vue')['default']
    StatusList: typeof import('./src/components/StatusList.vue')['default']
  }
}
